# Generated by Django 4.2.29 on 2026-08-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='created_data',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='massege',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='updated_data',
            new_name='updated_date',
        ),
    ]
